output "api_gateway_invoke_url" {
  description = "API Gateway base invoke URL. Use this as OwnTracks HTTP method's URL."
  value       = var.enable_api_gateway ? module.api_gateway[0].invoke_url : null
}

output "sqs_queue_url" {
  description = "SQS queue URL used by enabled ingestion methods."
  value       = module.sqs.queue_url
}

output "iot_endpoint" {
  description = "IoT Core endpoint for MQTT ingestion."
  value       = var.enable_iot_core ? module.iot_core[0].iot_endpoint : null
}

output "iot_topic_rule_name" {
  description = "IoT Core topic rule forwarding MQTT payloads to SQS."
  value       = var.enable_iot_core ? module.iot_core[0].topic_rule_name : null
}

output "iot_device_policy_name" {
  description = "IoT policy name used for OwnTracks clients."
  value       = var.enable_iot_core ? module.iot_core[0].device_policy_name : null
}

output "iot_certificate_arn" {
  description = "Created IoT certificate ARN when iot_create_certificate is enabled."
  value       = var.enable_iot_core && var.iot_create_certificate ? module.iot_core[0].certificate_arn : null
}

output "iot_certificate_pem" {
  description = "IoT certificate PEM generated by Terraform when enabled."
  value       = var.enable_iot_core && var.iot_create_certificate ? module.iot_core[0].certificate_pem : null
  sensitive   = true
}

output "iot_certificate_private_key" {
  description = "IoT certificate private key generated by Terraform when enabled."
  value       = var.enable_iot_core && var.iot_create_certificate ? module.iot_core[0].certificate_private_key : null
  sensitive   = true
}

output "iot_certificate_public_key" {
  description = "IoT certificate public key generated by Terraform when enabled."
  value       = var.enable_iot_core && var.iot_create_certificate ? module.iot_core[0].certificate_public_key : null
}

output "owntracks_mqtt_connection" {
  description = "MQTT connection values for OwnTracks when IoT Core ingestion is enabled."
  value = var.enable_iot_core ? format(
    "Host: %s\nPort: 8883\nTopic: %s",
    module.iot_core[0].iot_endpoint,
    replace(var.iot_topic_filter, "#", "<user>/<device>")
  ) : null
}

output "iot_manual_certificate_instructions" {
  description = "Manual certificate creation steps when iot_create_certificate is false."
  value       = var.enable_iot_core && !var.iot_create_certificate ? module.iot_core[0].manual_certificate_instructions : null
}

output "data_lake_bucket" {
  description = "S3 bucket containing partitioned JSONL location data."
  value       = module.s3.bucket_name
}

output "data_lake_prefix" {
  description = "Optional root prefix for location data inside the data lake bucket."
  value       = ""
}

output "aws_region" {
  description = "AWS region used by the core stack."
  value       = var.aws_region
}
